language: node_js
node_js:
  - "5.1"
cache:
  directories:
    - node_modules

before_script:
  - webpack
deploy:
  provider: heroku
  app: immense-waters-3264
  api_key:
    secure: tCRzx2GF6fir7gV5HtUKbiSdamp6dvl1uiV9yZKmRZa7wy11IUlhtevGhETBtXdTTTb2i1BK0WngJbSrVOtcsbF1xLMg+JHJbVlL7S6yaAVOYfEd6Z377pwiM38nRfV3N5vm8kWtFKONI4hsXNxANyENTquR8Wm7tldBlHydaa+Dz8VXfDWptqTvH8b52NSg5qOZspIGeVA9hhb/CQXNaK5y/+dsZiNTDsPGiWlmEaBrG+KuO47kmox5ZvY+OG3rScuBDvWGA8UHk/LjVdgFz7c6yYey5ursUNj55rzAeyCThqpLPy1i1K27LuS4gor0oUPi4GgxKaT/5ONe1jUbRn/nOFRPg3U555ueI5ExJ9QgwoPpdQGf04jRwBLoFdqRh29MAwQwwRTAjpOtlJr3fPj7wZwuwniVvotudATCiLBKhEubTpDN/3zvLQq8vabvYPxK878xfSnPG8IAoizRdelRyMy/zfff4eDEdJRFkNpy3sg2t60QtZKkvhlOWMhKWYB4/z5QaPcmKjNVEn5TADIonwqxJA8WF9vIeG+nwRO6kwoL7iRxVIyxk8drDmOjEAQJkRLV3C8PgEHKtsc3BZqOn7tJI5BbOJfLflzC16t37K22cC6dRmEMGgAXSk82lh43bT9gu5P3/vYf64DcGtQm7IBtOUEo74vuFEUx12U=
  skip_cleanup: true
